GET http://localhost:3000/healthz

###

POST http://localhost:3000/query
Content-Type: application/json

{
  "query": "What are the names of the users?"   
}

###

GET http://localhost:3000/debug/tool-cards

###

POST http://localhost:3000/debug/test-query
Content-Type: application/json

{
  "query": "create a new customer"
}

###

POST http://localhost:3000/query
Content-Type: application/json

{
  "query": "update a new customer with email jenny@example.com to have a new name jenny test test",
  "tool": "stripe"
}

###