GET http://localhost:3000/healthz

###

POST http://localhost:3000/query
Content-Type: application/json

{
  "query": "What are the names of the users?"   
}

###

GET http://localhost:3000/debug/tool-cards

###

POST http://localhost:3000/debug/test-query
Content-Type: application/json

{
  "query": "update a customer"
}

###

POST http://localhost:3000/query
Content-Type: application/json

{
  "query": "delete a customer with id cus_SGTYVpArCq5t2f",
  "tool": "stripe"
}

###